export const UPDATE_USERNAME = 'UPDATE_USERNAME';
export const SIGN_UP = 'SIGN_UP';
export const GET_ALL_LOCATIONS = 'GET_ALL_LOCATIONS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_PLACES_WANT_TO_VISIT = 'UPDATE_PLACES_WANT_TO_VISIT';
export const UPDATE_PLACES_VISITED = 'UPDATE_PLACES_VISITED';
